name: Build App
on:
  push:
jobs:
  build:
    runs-on: macos-latest
    steps:
     - uses: actions/checkout@v3
     - name: Git Push
       run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
            git clone -b arm64 https://github.com/wh1te4ever/kfund
            cp -r kfund/kfd/libkfd "My App/libkfd"
            rm "My App/libkfd.h"
            cp kfund/kfd/libkfd.h "My App/libkfd.h"
            git add "My App/libkfd"
            git add "My App/libkfd.h"
            git commit -m "Added exploit"
            git push
