name: Build App
on:
  push:
jobs:
  build:
    runs-on: macos-latest
    steps:
     - uses: actions/checkout@v3
     - name: Git Push
       run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
            git clone https://github.com/AppInstalleriOSGH/Taurine
            cp -r Taurine/Taurine/exploit/kfd kfd
            git add kfd
            git commit -m "Added exploit"
            git push
