name: Build App
on:
  push:
jobs:
  build:
    runs-on: macos-latest
    steps:
     - uses: actions/checkout@v3
     - name: Git Push
       run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
            git clone -b sync-upstream https://github.com/opa334/kfd
            cp -r kfd/kfd/libkfd "My App/libkfd"
            cp kfd/kfd/libkfd.h "My App/libkfd.h"
            git add "My App/libkfd"
            git add "My App/libkfd.h"
            git commit -m "Added exploit"
            git push
